### PR TITLE
Fix for review history not recording new reviews

### PR DESCRIPTION
**Pull request by mariomc**
Without jQuery, the functionality was stuck in an endless setTimeout loop! 😄

### CODE REVIEW

**Comment by Paranomix** [comment]
Now recording, but nominations are always "expired".

**Comment by mariomc** [comment]
> Now recording, but nominations are always "expired".

This is due to the fact that this setTimeout...
https://github.com/MrJPGames/WayFarerPlus/blob/f680fc60e3517c5f56046213d969424a53eae87d/pageJs/profile/recordReviews.js#L1-L7

resolves after the "WFPAnsCtrlHooked" event is triggered. Which means that no review data is saved along with it. Will probably need to work a bit more on this PR though.

**Comment by MrJPGames** [comment]
Could you maybe take a look at 9ba2231d5d28a5309b6de01f86ce4a07cc303614?

I believe this should be a temporary hack that works for the time being, until I get the time to implement a more solid solution.

The main difference is that now instead of waiting for jQuery to load and then hooking events, events are hooked upon loading of the script and after the pCtrl event is triggered we wait for jQuery if necessary. This should work as only the profile page actually uses jQuery.

**Comment by MrJPGames** [comment]
As this issue is already resolved if I'm not mistaken I will be closing this PR. If I am mistaken feel free to request a reopen!

**Pull request closed without merging**
