### PR TITLE
feature: Review History

### LINKED ISSUE #80: Save Review History and allow GeoJSON export
**Describe the feature you'd like**
There was an OPR userscrupt called opr-portal-tracker (https://www.reddit.com/r/Ingress/comments/9bds6k/opr_portal_tracker_userjs_to_track_locations/) . It would keep a geo log of what you reviewed, and how you reviewed it. I'd like that functionality to be added into this chrome extension

**Describe reasons NOT to add this feature**
There could be an argument made that Niantic wouldn't want us to do this. 

**Describe reasons to add this feature**
Being able to look back on the things you reviewed can be not only a cool bit of data, but it can be insightful to see whether a nomination you previously reviewed ultimately ended up getting accepted or not. Being able to look at your previous reviews, then viewing that nomination in the Ingress Intel map (to see if it ended up being accepted) would let you get a better idea of how you're voting on certain things compared to the majority of Wayfarer. 

**Additional context**
The export as GeoJSON was the coolest part, which you can see as a gist on my profile from when I was using this before. https://gist.github.com/fortepc/bdb8078c4cea3855261524564fcd0ae8

### PR DESCRIPTION
**Pull request by mariomc**
Closes #80 .
Adds a feature to support the **local** recording of your Review History. This includes which candidates you evaluated, when, and which score, actions ("Mark as Duplicate", "Skip", Time out) you've given.
It also adds to your profile both a map and table to explore those same evaluations.

Screenshot 2020-03-16 at 01 10 58
Screenshot 2020-03-16 at 01 11 23
Screenshot 2020-03-16 at 01 06 48

Tasks done:
- [x] Saved candidate data in localStorage
- [x] Build a list of reviewed candidates in profile
- [x] Build a map of the candidate reviews 
- [x] Build a list of the candidate reviews 
- [x] Export history to geoJSON  
- [x] Ability to delete history 
- [x] Show candidate data on a map popup
- [x] Save and show review decisions/scores
- [x] Link to Intel.
- [x] Ability to manually mark nomination as accepted (helps keep track of agreements)
- [x] Color coded markers per-rating given
- [x] Correctly handle "Mark as duplicate" requests and show them properly

Saved for a future Release: 
- Save and show edits (Different schema)
- Represent new positions in map

### CODE REVIEW

**Comment by MrJPGames** [comment]
I've also made a few small modifications (to map controls, and page styling). How about we combine your 2 features with some upkeep and minor feature additions of mine and call it 1.12?

**Comment by mariomc** [comment]
> I've also made a few small modifications (to map controls, and page styling). How about we combine your 2 features with some upkeep and minor feature additions of mine and call it 1.12?

If you're ok to wait until tomorrow, we can see how this body of work has progressed then (still WIP, currently stuck at finding a clean way to yank the review scores out) and can release them in batch after that or just go as is if this turns out trickier than I thought 😅

**Comment by MrJPGames** [comment]
I'm fine with waiting until it's finished!

Have you tried hooking yourself to submitForm(), confirmLowQuality() and markDuplicate()?

**Comment by mariomc** [comment]
> submitForm

That sounds like a good idea. Will do just that. Thanks!

**Comment by mariomc** [comment]
Only missing the duplicates so far. Still have to find a stream of duplicates in order to test. I guess I'll save the edits for a future revisit of this feature as they represent a whole different complexity altogether.

**Comment by mariomc** [comment]
Finished!
Will leave the self-imposed feature creep (support for edits and new location) for another spin!

**Comment by mariomc** [comment]
A few caveats with the latest PRs, though. Since I use a few new features of the language, the support for this feature (and the previous one I've open) is Chrome 60+ or Firefox 55+.
This might change the overall support of the extension. But given that those are almost three years old (and are evergreen) it should be fine.

**Comment by MrJPGames** [comment]
Yep should be no issue at all. The only versions officially supported are the very latest, it's nice if it works on older versions but it's not a priority at the moment.

I'll take a closer look tomorrow at your work as I'm very busy with study right now. But from the bits and pieces I've seen it looks very promising!

**Comment by mariomc** [comment]
> Yep should be no issue at all. The only versions officially supported are the very latest, it's nice if it works on older versions but it's not a priority at the moment.
> 
> I'll take a closer look tomorrow at your work as I'm very busy with study right now. But from the bits and pieces I've seen it looks very promising!

Sure thing! If you need any clarifications, reach out here, at Twitter ( `@mariomc` ) or in Telegram ( `Stultusz` ).

**Comment by MrJPGames** [comment]
Sorry for being a day late! First of all now that I've gotten the time to actually look at your work it's absolutely amazing! The feature looks very clean and is very nicely done!

There are two things I'll do after merging though:
- Firstly the table though not unreadable doesn't look great in dark mode (due to Wayfarer's default bootstrap.css), so I'll make a simple change in the dark mode to cover this.
- Secondly currently the setting is under profile, which I understand but I feel it would fit better under review. It could technically also be in both locations without issue. Please let me know what you think about this decision!

**Comment by mariomc** [comment]
> Sorry for being a day late! First of all now that I've gotten the time to actually look at your work it's absolutely amazing! The feature looks very clean and is very nicely done!
>

Take your time. Thanks! 
 
> There are two things I'll do after merging though:
> 
> * Firstly the table though not unreadable doesn't look great in dark mode (due to Wayfarer's default bootstrap.css), so I'll make a simple change in the dark mode to cover this.

Sure thing, I hadn't tested it with black mode. My bady! Bootstrap has a lot of classes that might help around in that sense.

> * Secondly currently the setting is under profile, which I understand but I feel it would fit better under review. It could technically also be in both locations without issue. Please let me know what you think about this decision!

Yeah, I debated with that as well. The reasoning for it being under profile is that it's where the recorded information actually _shows_. But the feature is indeed a **Review** history, so I'm torn.
I believe we can move it into review and add a note to the info in the feature toggle saying something in the lines of "You can check the reviews done while this feature was turned on, in your Profile page". How does that sound?

**Pull request merged**
